import { Cafe } from '@/types';

const defaultHours = (open: string, close: string) => ({
  monday: { open, close, closed: false },
  tuesday: { open, close, closed: false },
  wednesday: { open, close, closed: false },
  thursday: { open, close, closed: false },
  friday: { open, close: `${parseInt(close) + 1}:00`, closed: false },
  saturday: { open: `0${parseInt(open) + 1}:00`, close: `${parseInt(close) + 1}:00`, closed: false },
  sunday: { open: `0${parseInt(open) + 1}:00`, close, closed: false },
});

export const MOCK_CAFES: Cafe[] = [
  {
    id: '1',
    name: 'Pagdandi Books Chai Café',
    description: 'A cozy literary café perfect for deep work sessions. Surrounded by books with excellent chai and a hushed atmosphere that devs love.',
    address: 'Baner-Pashan Link Rd, Bavdhan',
    neighborhood: 'Bavdhan',
    lat: 18.5158,
    lng: 73.7762,
    amenities: ['wifi', 'power_outlets', 'quiet_zone', 'good_coffee'],
    wifi_speed_mbps: 40,
    noise_level: 'quiet',
    power_outlets: 'few',
    rating: 4.7,
    review_count: 128,
    images: [],
    opening_hours: {
      monday: { open: '09:00', close: '22:00', closed: false },
      tuesday: { open: '09:00', close: '22:00', closed: false },
      wednesday: { open: '09:00', close: '22:00', closed: false },
      thursday: { open: '09:00', close: '22:00', closed: false },
      friday: { open: '09:00', close: '23:00', closed: false },
      saturday: { open: '09:00', close: '23:00', closed: false },
      sunday: { open: '10:00', close: '21:00', closed: false },
    },
    price_range: 1,
    phone: null,
    website: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'The Flour Works',
    description: 'Bright, modern café popular with the startup crowd. Fast fibre WiFi, ample power points, and the best brunch in Kalyani Nagar.',
    address: '3, Lakeview Colony, Kalyani Nagar',
    neighborhood: 'Kalyani Nagar',
    lat: 18.5498,
    lng: 73.9024,
    amenities: ['wifi', 'power_outlets', 'food', 'good_coffee', 'outdoor_seating'],
    wifi_speed_mbps: 80,
    noise_level: 'moderate',
    power_outlets: 'plenty',
    rating: 4.5,
    review_count: 214,
    images: [],
    opening_hours: {
      monday: { open: '08:00', close: '22:00', closed: false },
      tuesday: { open: '08:00', close: '22:00', closed: false },
      wednesday: { open: '08:00', close: '22:00', closed: false },
      thursday: { open: '08:00', close: '22:00', closed: false },
      friday: { open: '08:00', close: '23:00', closed: false },
      saturday: { open: '09:00', close: '23:00', closed: false },
      sunday: { open: '09:00', close: '21:00', closed: false },
    },
    price_range: 2,
    phone: null,
    website: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Café Goodluck',
    description: "A Pune institution since 1935. Iconic bun maska and Irani chai. No WiFi — but pure focus fuel.",
    address: 'Deccan Gymkhana, FC Road',
    neighborhood: 'Deccan',
    lat: 18.5079,
    lng: 73.8394,
    amenities: ['food', 'good_coffee'],
    wifi_speed_mbps: null,
    noise_level: 'lively',
    power_outlets: 'none',
    rating: 4.3,
    review_count: 512,
    images: [],
    opening_hours: {
      monday: { open: '07:00', close: '22:30', closed: false },
      tuesday: { open: '07:00', close: '22:30', closed: false },
      wednesday: { open: '07:00', close: '22:30', closed: false },
      thursday: { open: '07:00', close: '22:30', closed: false },
      friday: { open: '07:00', close: '22:30', closed: false },
      saturday: { open: '07:00', close: '22:30', closed: false },
      sunday: { open: '07:00', close: '22:30', closed: false },
    },
    price_range: 1,
    phone: null,
    website: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Café Peter',
    description: 'Serene café in the heart of Koregaon Park. Great for focused work with lush outdoor seating and reliable WiFi.',
    address: 'Lane 5, Koregaon Park',
    neighborhood: 'Koregaon Park',
    lat: 18.5285,
    lng: 73.8929,
    amenities: ['wifi', 'power_outlets', 'outdoor_seating', 'food', 'good_coffee'],
    wifi_speed_mbps: 50,
    noise_level: 'quiet',
    power_outlets: 'few',
    rating: 4.4,
    review_count: 189,
    images: [],
    opening_hours: {
      monday: { open: '08:00', close: '22:00', closed: false },
      tuesday: { open: '08:00', close: '22:00', closed: false },
      wednesday: { open: '08:00', close: '22:00', closed: false },
      thursday: { open: '08:00', close: '22:00', closed: false },
      friday: { open: '08:00', close: '23:00', closed: false },
      saturday: { open: '09:00', close: '23:00', closed: false },
      sunday: { open: '09:00', close: '21:00', closed: false },
    },
    price_range: 2,
    phone: null,
    website: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Coffee Culture',
    description: 'A developer favourite near Hinjewadi. Gigabit WiFi, power strips at every table, and parking for your commute.',
    address: 'Wakad-Hinjewadi Rd, Wakad',
    neighborhood: 'Wakad',
    lat: 18.5893,
    lng: 73.7686,
    amenities: ['wifi', 'power_outlets', 'quiet_zone', 'parking', 'good_coffee'],
    wifi_speed_mbps: 120,
    noise_level: 'quiet',
    power_outlets: 'plenty',
    rating: 4.6,
    review_count: 97,
    images: [],
    opening_hours: {
      monday: { open: '07:30', close: '22:00', closed: false },
      tuesday: { open: '07:30', close: '22:00', closed: false },
      wednesday: { open: '07:30', close: '22:00', closed: false },
      thursday: { open: '07:30', close: '22:00', closed: false },
      friday: { open: '07:30', close: '23:00', closed: false },
      saturday: { open: '08:00', close: '23:00', closed: false },
      sunday: { open: '08:00', close: '21:00', closed: false },
    },
    price_range: 2,
    phone: null,
    website: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Vohuman Café',
    description: 'Classic Irani café with the best brun maska in Pune. Opens at 6:30 AM — ideal for early-bird coding sessions over chai.',
    address: 'Sassoon Rd, Camp',
    neighborhood: 'Camp',
    lat: 18.5121,
    lng: 73.8820,
    amenities: ['food', 'good_coffee'],
    wifi_speed_mbps: null,
    noise_level: 'lively',
    power_outlets: 'none',
    rating: 4.8,
    review_count: 891,
    images: [],
    opening_hours: {
      monday: { open: '06:30', close: '11:00', closed: false },
      tuesday: { open: '06:30', close: '11:00', closed: false },
      wednesday: { open: '06:30', close: '11:00', closed: false },
      thursday: { open: '06:30', close: '11:00', closed: false },
      friday: { open: '06:30', close: '11:00', closed: false },
      saturday: { open: '06:30', close: '11:00', closed: false },
      sunday: { open: '06:30', close: '11:00', closed: false },
    },
    price_range: 1,
    phone: null,
    website: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Third Wave Coffee',
    description: 'Minimalist specialty café with pour-overs and 100 Mbps fibre. Wide tables built for laptops and long sprints.',
    address: 'Aundh Rd, Aundh',
    neighborhood: 'Aundh',
    lat: 18.5590,
    lng: 73.8077,
    amenities: ['wifi', 'power_outlets', 'quiet_zone', 'good_coffee', 'parking'],
    wifi_speed_mbps: 100,
    noise_level: 'quiet',
    power_outlets: 'plenty',
    rating: 4.5,
    review_count: 143,
    images: [],
    opening_hours: {
      monday: { open: '08:00', close: '22:00', closed: false },
      tuesday: { open: '08:00', close: '22:00', closed: false },
      wednesday: { open: '08:00', close: '22:00', closed: false },
      thursday: { open: '08:00', close: '22:00', closed: false },
      friday: { open: '08:00', close: '22:00', closed: false },
      saturday: { open: '09:00', close: '23:00', closed: false },
      sunday: { open: '09:00', close: '22:00', closed: false },
    },
    price_range: 2,
    phone: null,
    website: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Kalmane Koffee',
    description: 'Estate-grown South Indian coffee roasted in-house. The quiet first floor is unbeatable for deep work on a weekday morning.',
    address: 'SB Road, Shivajinagar',
    neighborhood: 'Shivajinagar',
    lat: 18.5308,
    lng: 73.8475,
    amenities: ['wifi', 'power_outlets', 'quiet_zone', 'good_coffee'],
    wifi_speed_mbps: 60,
    noise_level: 'moderate',
    power_outlets: 'few',
    rating: 4.4,
    review_count: 76,
    images: [],
    opening_hours: {
      monday: { open: '09:00', close: '21:30', closed: false },
      tuesday: { open: '09:00', close: '21:30', closed: false },
      wednesday: { open: '09:00', close: '21:30', closed: false },
      thursday: { open: '09:00', close: '21:30', closed: false },
      friday: { open: '09:00', close: '21:30', closed: false },
      saturday: { open: '09:00', close: '22:00', closed: false },
      sunday: { open: '09:00', close: '21:00', closed: false },
    },
    price_range: 2,
    phone: null,
    website: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
